version: 2.1

orbs:
  node: circleci/node@6.1.0
jobs:
  test:
    executor: 
      name: node/default
      tag: '20'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Run build
workflows:
  test-my-app:
    jobs:
      - test
